### ISSUE TITLE
Feature Request: Add WebSocket Support

### ISSUE THREAD

**Issue by iamxvbaba** [shenghui0779/yiirs#5]
Description:
I would like to propose adding WebSocket support to the framework. 

Motivation:
- Enable real-time bidirectional communication between client and server
- Support common use cases like live updates and chat functionality
- Enhance the framework's capabilities for modern web applications

Suggested Implementation:
- Add a WebSocket handler system
- Support both ws:// and wss:// protocols
- Provide basic connection management utilities
- Include simple examples for common WebSocket patterns

**Comment by shenghui0779** [comment]
Good suggestion！

**Comment by shenghui0779** [comment]
- salvo
Reference https://github.com/salvo-rs/salvo/blob/main/examples/websocket/src/main.rs

- axum
Reference https://github.com/tokio-rs/axum/blob/main/examples/websockets/src/main.rs
