### ISSUE TITLE
Feature Request: Add File Upload/Download Functionality

### ISSUE THREAD

**Issue by iamxvbaba** [shenghui0779/yiirs#6]
Description:
I would like to propose adding built-in support for file upload and download operations.

Motivation:
- Simplify implementation of file handling features
- Provide a standard way to handle common file operations
- Reduce boilerplate code for developers

Suggested Implementation:
- Support multipart/form-data uploads
- Add stream-based file download handling
- Include progress tracking capabilities
- Add configurable file size limits
- Provide validation helpers for file types

**Comment by shenghui0779** [comment]
Good suggestion！

**Comment by shenghui0779** [comment]
- salvo
Reference https://github.com/salvo-rs/salvo/blob/main/examples/upload-file/src/main.rs
